### ISSUE TITLE
[Epic: Status] Enable testing of direct messages in unreliable networks

### ISSUE THREAD

**Issue by chair28980** [waku-org/go-waku#1234]
## Tasks

- [x] https://github.com/status-im/status-go/issues/5143
- [x] https://github.com/status-im/status-go/issues/5144
- [x] https://github.com/status-im/status-go/pull/5317
- [x] https://github.com/status-im/status-go/pull/5318
- [x] https://github.com/status-im/status-go/pull/5329
- [x] https://github.com/status-im/status-go/pull/5351
- [x] https://github.com/status-im/status-go/pull/5407
