### ISSUE TITLE
[Milestone] RLN: Post-Testnet3 Improvements

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#605]
**Planned start date**:
**Due date**:

# Summary

go-waku's RLN feature has fallen behind compared to nwaku. Code equivalent to the following PRs from nwaku must be implemented for go-waku's to be up to date with RLN functionality and also allowing it to be used with the simulation tools

- [x] https://github.com/waku-org/nwaku/issues/1733
- [x] https://github.com/waku-org/nwaku/issues/1777
- [x] https://github.com/waku-org/nwaku/issues/1805
- [x] https://github.com/waku-org/nwaku/issues/1838 
- [x] https://github.com/waku-org/nwaku/issues/1844

# Acceptance Criteria

- [x] Feature parity
- [x] Interop is achieved between nwaku and go-waku with messages going back and forth between chat2 clients
  - [x] go-waku chat2 -> go-waku relay node -> nwaku chat2
  - [x] go-waku chat2 -> nwaku relay node -> go-waku chat2
  - [x] [ensure credentials generated in nwaku work in go-waku and viceversa](https://github.com/waku-org/go-waku/pull/640)

## Tasks

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by richard-ramos** [comment]
#1777 implemented in https://github.com/waku-org/go-waku/pull/615

**Comment by richard-ramos** [comment]
#1838 implemented in https://github.com/waku-org/go-waku/pull/612

**Comment by richard-ramos** [comment]
#1844 implemented in https://github.com/waku-org/go-waku/pull/616

**Comment by fryorcraken** [comment]
@rymnc are all the functionality listed the one you delivered for testnet 3? I wonder if we can scope this issue to reach testnet 3 feature equivalence.

**Comment by rymnc** [comment]
Yes, and the following are the issues sorted from the retrospective post-testnet 3

https://github.com/vacp2p/research/issues/179#issuecomment-1579202451

**Comment by richard-ramos** [comment]
nwaku#1733 implemented in #617

**Comment by richard-ramos** [comment]
**Weekly Update**

_achieved_: use zerokit batch insert/delete for members, exposed function to retrieve data from merkle tree, modified zerokit and go-zerokit-rln to pass merkle tree persistance configuration settings
_next_: resume onchain sync from persisted tree db
_blocker_: none

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: expose merkle tree configuration, remove embedded resources from go-zerokit-rln, fix nwaku / go-waku rlnKeystore compatibility, add merkle tree persistence, modify zerokit to print to stderr any error obtained while executing functions via FFI.
- _next_: store only last 10 epochs in nullifier log

**Comment by richard-ramos** [comment]
Weekly Update

    achieved: interop with nwaku.
