### ISSUE TITLE
feat: Auto-sharding v1

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#623]
**Planned start date**: 
**Due date**:  

# Summary

Implement AutoSharding as per https://github.com/waku-org/nwaku/issues/1846

Refer to following Pr's from nwaku

https://github.com/waku-org/nwaku/pull/1854/
https://github.com/waku-org/nwaku/pull/1856
https://github.com/waku-org/nwaku/pull/1857/
https://github.com/waku-org/nwaku/pull/1902

# Acceptance Criteria

- [x] Validate autosharding function's distribution of content topics to shards.
- [x] The ENR of node using autoshard is created/updated with the shards info.
- [x] Nodes can be configured for content topics and/or pubsub topics.

## Tasks

- [x] https://github.com/waku-org/go-waku/pull/669
- [x] #696 

# RAID

**Comment by chaitanyaprem** [comment]
Weekly Update
- achieved: Implemented core logic for autosharding
- next: API changes for autosharding

**Comment by chaitanyaprem** [comment]
Closing this issue as further autosharding related items are tracked as separate issues.
