### ISSUE TITLE
RLN enabled by default

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/go-waku#655]
**Planned start date**:
**Due date**:

# Summary

RLN validation should be enabled by default for relay nodes

# Acceptance Criteria

## Tasks
- [x] Run rln-relay on all configured pubsub topics and content topics (passed in w/ `--pubsub-topic`)
- [ ] Separate out bandwidth constraint validator 
- [x] Ordered validator execution
  1. WakuMessage decoding
  2. WakuRelay
  3. WakuRlnRelay
- [x] Review metrics (few too many one-time metrics, like startup time etc)
- [x] Clear up the nullifier table (clear the table once in 10 epochs or so)
- [x] Health check api (`/health` should denote if the nwaku node is ready for use)
- [x] Sync from the deployment block instead of from genesis. 
- [x] The `rln` feature should be available in the non-experimental context
- [x] Add metric to show the amout of registered memberships in the tree.
- [x] Rename rlnkeystore application to `waku-rln-relay`
- [x] Remove registration capability from go-waku
- [x] RLN DB should be aware of chain and contract address
- [x] Command to generate keystores
- [x] Add metric with the total registered memberships in the contract 
- [x] `s/flush_interval/flush_every_ms` misconfiguration on rln config 
- [x] DB should be aware of chain and contract address 
- [x] DB dissapears (use zerokit v0.3.2)
- [x] Sync valid roots to metadata
- [x] Non deterministic sorting applied to credentials, and contract
- [ ] Mobile support for RLN https://github.com/waku-org/go-zerokit-rln/issues/5 
- [ ] C-Bindings support for RLN #732 
- [x] Nix build support for RLN #731 

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: removed registration capability from the wakunode and created a separate subcommand to do the registration
- _next_: run rln-relay on all configured pubsub topics and content topics

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: run rln-relay on all configured pubsub topics and content topics, added metrics, made RLN database aware of chainID and contract address, refactored keystore.
- _next_:  test keystore interop with nwaku, integrate waku rln registry, and restore valid roots from DB

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: test keystore interop with nwaku, integrate waku rln registry, and restore valid roots from DB
- _next_:  ordered validator execution, bandwidth validation, upgrade zerokit

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: ordered validator execution, upgrade zerokit, append rln proofs when posting msgs in rest/rpc, clean up nullifier table, automatically use key from keystore if only a single credential is available, validate credential using onchain query
- _next_:  bandwidth validation, rln isReady verif in /health endpoint, subcommand to list credentials

**Comment by richard-ramos** [comment]
Added https://github.com/waku-org/go-zerokit-rln/issues/5 . Might make sense to extract this to a separate epic, as mobile support is not really a priority for now

**Comment by richard-ramos** [comment]
Added https://github.com/waku-org/go-waku/issues/732 since c-bindings fail to compile when RLN support is added by default

**Comment by richard-ramos** [comment]
Added #731 since nix is failing to build go-waku when RLN support is added by default

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: isReady verif in /health endpoint,  make RLN available in service nodes and library usage by default, update docs and docker image, use zerokit 0.3.4, allow running service node with no RLN credentials 
- _next_:  bandwidth validation, subcommand to list credentials

**Comment by chair28980** [comment]
Closing issue per discussion with Richard the critical for launch tasks in this issue have been completed. The remaining open tasks will be added to the catch-all non-critical Epic.
