### ISSUE TITLE
Feat: Intelligent Sharded Peer Management and Config

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/go-waku#771]
# Summary

Basic Sharded Peer discovery and Management is captured under #727 . 
This issue covers more advanced scope for sharded peer management which is not of immediate priority, but is a good to have in the long run. 

This covers having some kind of peer scoring based on which peer selection/disconnections are done for shards. 
This also includes shard level configuration that could be specified wrt peer-connections, service support etc.

Refer discussion here https://discord.com/channels/1110799176264056863/1154764025301844018 

# Acceptance Criteria

- [ ] Validate scoring algorithm
- [ ] Define separate shard level config

## Tasks

- [ ] Shard level configuration
- [ ] Using configuration profiles (similar to ipfs) - Probably have to be segregated into its own issue. 
- [ ] Peer selection/pruning based on peer scoring (To analyze what parameters are to be considered for scoring)
- [ ] Soft and hard limits on connection management (To analyze)

**Comment by chair28980** [comment]
Removing from Gen-0 Milestone per discussion with go-waku team.

**Comment by chaitanyaprem** [comment]
Closing the issue as it is descoped for go-waku.
